### ISSUE TITLE
Windows Server 2003 VM support

### ISSUE THREAD

**Issue by Zero3K** [gigaherz/nvmewin#1]
It would be nice if it you could get it to work in a x86/x64 Windows Server 2003 VM. I tried the version available at https://sourceforge.net/projects/nvme-for-windows-2003-server/ (which didn't work in either architecture). It gave me a "Code 10" error in its Properties that is available via Device Manager and froze the OS when trying to boot with a disk image associated to the NVMe controller that I had added to the VM's settings (both VMWare Workstation Player 15 and VirtualBox resulted in the same thing happening).

**Comment by gigaherz** [comment]
I mirrored that svn repository as a backup, since the page was kindof dead. Seems the status hasn't changed, and there's no new commits.
I can't categorically say that I will never ever touch this code, but yeah, don't keep your hopes high.

**Comment by Zero3K** [comment]
Oh, it would allow it to work on ReactOS if support for Windows Server 2003 was added. How would I go about compiling for Windows Server 2003 in Visual Studio 2017 on Windows 10 so I can see what errors it generates?

**Comment by Zero3K** [comment]
Any news?
